from pynput.keyboard import Key, Controller
import time

keyboard = Controller()

keyboard.press(Key.cmd)
keyboard.press('r')
keyboard.release('r')
keyboard.release(Key.cmd)
time.sleep(0.21)

keyboard.type("cmd")
time.sleep(0.51)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)

time.sleep(0.5)

keyboard.type("color a")
time.sleep(0.21)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)
time.sleep(0.1)
keyboard.type("  dir /s")
time.sleep(0.21)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)

time.sleep(0.11)

keyboard.press(Key.cmd)
keyboard.press('r')
keyboard.release('r')
keyboard.release(Key.cmd)
time.sleep(0.1)

keyboard.type("cmd")
time.sleep(0.51)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)

time.sleep(0.5)

keyboard.type("color 4")
time.sleep(0.21)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)
time.sleep(0.1)
keyboard.type("  dir /s")
time.sleep(0.21)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)

time.sleep(0.1)

keyboard.press(Key.cmd)
keyboard.press('r')
keyboard.release('r')
keyboard.release(Key.cmd)
time.sleep(0.1)

keyboard.type("cmd")
time.sleep(0.51)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)

time.sleep(0.5)

keyboard.type("color 5")
time.sleep(0.21)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)
time.sleep(0.1)
keyboard.type("  dir /s")
time.sleep(0.21)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)

time.sleep(1.1)


keyboard.press(Key.cmd)
keyboard.press('r')
keyboard.release('r')
keyboard.release(Key.cmd)

time.sleep(1)

keyboard.type("notepad")
time.sleep(0.21)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)
time.sleep(0.5)
keyboard.press(Key.enter)
time.sleep(0.1)
keyboard.release(Key.enter)
time.sleep(0.21)

time.sleep(1)
for i in range(50):
    keyboard.type("YOU JUST GOT HACKED!!!")
    keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.type("jk lol u can trust me that this is just an offline one time thing,")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.type("i actually have morals and shit so i would never do anything bad man :/")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.type("ppl deserve privacy :)")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.type("Close this and be careful with shit from now on :/")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.type("Program delete nahi karna. \nKia to ill know.. ghar aa ke maru ga.\nlaters!")
